---
kiosk_url: https://sqq-sdl.staging.foodcoop12.trobz.com/pos/web?config_id=1
kiosk_mode: no

firefox_policies_extra:
  DisableDeveloperTools: false
  BlockAboutConfig: false
  BlockAboutAddons: false

firefox_policies_whitelist: []
