---
- name: Install dynamic display configuration
  ansible.builtin.copy:
    src: autokanshi.py
    dest: /usr/local/bin/autokanshi
    mode: "0755"

- name: Deploy udev scheduler rules
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/70-autokanshi.rules
    mode: "0644"
    content: |
      SUBSYSTEM=="drm", ACTION=="change", RUN+="/usr/local/bin/autokanshi --write-to /etc/kanshi/config"
  notify: reload-udev-rules

- name: Configure kanshi service
  ansible.builtin.template:
    src: "kanshi.service.j2"
    dest: "/etc/systemd/system/kanshi.service"
  notify:
    - systemd-daemon-reload
    - restart-kanshi

- name: Enable kanshi service
  ansible.builtin.systemd_service:
    name: kanshi.service
    enabled: true
