---
- name: Gather service facts
  ansible.builtin.service_facts:

- name: Create kiosk user
  ansible.builtin.user:
    name: "{{ kiosk_user }}"
    uid: "{{ kiosk_userid }}"
    groups: "video,input,render"
    shell: /bin/bash
    create_home: true

- name: Install graphical packages
  ansible.builtin.apt:
    name:
      - cage
      - kanshi
      - firefox-esr
    state: present

- name: Deploy service configuration
  ansible.builtin.include_tasks: "{{ service }}.yml"
  loop:
    - cage
    - kanshi
    - firefox
  loop_control:
    loop_var: service
