---
- name: Install docker tooling
  ansible.builtin.include_tasks: docker.yml

- name: Create posbox directory
  ansible.builtin.file:
    path: "{{ posbox_dir }}"
    state: directory

- name: Deploy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ posbox_dir }}/docker-compose.yml"

- name: Configure posbox containers
  ansible.builtin.copy:
    dest: "{{ posbox_dir }}/.env"
    mode: 0600
    content: |
      POSTGRES_DB={{ posbox_database }}
      POSTGRES_USER={{ posbox_username }}
      POSTGRES_PASSWORD={{ posbox_password }}

- name: Configure posbox proxy container
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ posbox_dir }}/traefik.yml"

- name: Start posbox containers
  community.docker.docker_compose_v2:
    project_src: "{{ posbox_dir }}"
    state: present
    pull: always
    remove_orphans: true

- name: Cleanup old docker images
  community.docker.docker_prune:
    images: yes
    images_filters:
      dangling: false
