---
- name: Install docker tooling
  ansible.builtin.include_tasks: docker.yml

- name: Create posbox directory
  ansible.builtin.file:
    path: "{{ posbox_dir }}"
    state: directory

- name: Deploy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ posbox_dir }}/docker-compose.yml"

- name: Start posbox containers
  community.docker.docker_compose_v2:
    project_src: "{{ posbox_dir }}"
    state: present
    pull: always
    remove_orphans: true

- name: Cleanup old docker images
  community.docker.docker_prune:
    images: yes
    images_filters:
      dangling: false
