- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
  listen: systemd-daemon-reload

- name: Reload udev rules
  ansible.builtin.shell: |
    udevadm control --reload-rules && \
    udevadm trigger --subsystem-match=drm
  listen: reload-udev-rules

- name: Restart cage service on tty1
  systemd:
    name: cage@tty1.service
    state: restarted
  when:
    - ansible_facts.services['cage@tty1.service'] is defined
    - ansible_facts.services['cage@tty1.service'].state == "running"
  listen: restart-cage

- name: Restart kanshi
  systemd:
    name: kanshi.service
    state: restarted
  when:
    - ansible_facts.services['kanshi.service'] is defined
    - ansible_facts.services['kanshi.service'].state == "running"
  listen: restart-kanshi
