---
- name: Set hostname from machine-id
  ansible.builtin.hostname:
    name: "kiosk-{{ ansible_default_ipv4.address.split('.')[-1] }}"

- name: Synchronize /etc/hosts with new hostname
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1\t{{ ansible_hostname }}"
    state: present

- name: Force a silent Grub boot
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash loglevel=3 rd.systemd.show_status=false rd.udev.log_priority=3 vt.global_cursor_default=0"'
    state: present
  notify: update-grub

- name: "Deactivate static motd"
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^session\s+optional\s+pam_motd\.so\s+noupdate'
    state: absent

- name: Deactivate dynamic uname motd
  ansible.builtin.file:
    path: /etc/update-motd.d/10-uname
    mode: "0444"

- name: Deploy dynamic kiosk motd
  ansible.builtin.template:
    src: "20-superquinquin.sh"
    dest: "/etc/update-motd.d/20-superquinquin"
    mode: "0755"
