---
- name: Configure kiosk
  hosts: all
  become: true

  roles:
    - { role: installer, tags: [system, installer] }
    - { role: system, tags: [system] }
    - { role: kiosk, tags: [apps, kiosk] }
